# Generated by Django 5.0.6 on 2024-07-10 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="project",
            name="start_date",
        ),
    ]
