# Generated by Django 5.0.6 on 2024-07-10 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_remove_project_end_date_remove_project_start_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["created_at", "status"],
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
    ]
