# Generated by Django 5.0.6 on 2024-07-10 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_alter_project_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
    ]
