version: '3.12'

services:
  web:
    build: .
    command: gunicorn workdiary.wsgi:application --bind 0.0.0.0:8080
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    env_file:
      - .env
