# Generated by Django 5.0.6 on 2024-06-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_alter_client_options_alter_client_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="client_reference",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
