# Generated by Django 5.0.6 on 2024-08-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_is_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_ceo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_employee",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_manager",
            field=models.BooleanField(default=False),
        ),
    ]
