# Generated by Django 5.0.6 on 2024-08-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_is_ceo_user_is_employee_user_is_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_personal",
            field=models.BooleanField(default=False),
        ),
    ]
