# Generated by Django 5.0.6 on 2024-07-10 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_due_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
            },
        ),
    ]
