# Generated by Django 5.0.6 on 2024-08-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="field",
            field=models.CharField(default="technology", max_length=255),
            preserve_default=False,
        ),
    ]
