# Generated by Django 5.0.6 on 2024-08-15 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_alter_company_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="employees",
            field=models.ManyToManyField(
                blank=True, related_name="company", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="companies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
