# Generated by Django 5.0.6 on 2024-08-15 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timesheets", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="timesheet",
            options={
                "ordering": ["-date"],
                "verbose_name": "Timesheet",
                "verbose_name_plural": "Timesheets",
            },
        ),
    ]
