# Generated by Django 5.0.6 on 2024-08-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timesheets", "0002_alter_timesheet_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="timesheet",
            name="overtime_hours",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
