# Generated by Django 5.0.6 on 2024-08-17 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0002_schedule_overtime_threshold"),
        ("timesheets", "0003_timesheet_overtime_hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timesheet",
            name="shift",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shift_timesheets",
                to="schedules.schedule",
            ),
        ),
    ]
