# Generated by Django 5.0.6 on 2024-08-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="overtime_threshold",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Number of hours after which overtime applies.",
                max_digits=5,
            ),
        ),
    ]
